version: '3.9'

services:
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: backend
    depends_on: 
      - mongo_db

volumes:
  mongo_data: {}