version: '3.9'

services:
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=$DB_USER
    #   - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - ./init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js
      - mongo_data:/data/db
    stdin_open: true
    tty: true

  mongo_express:
    image: mongo-express:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=$DB_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$DB_PASSWORD
    depends_on:
      - mongo_db

  api:
    build: .
    ports:
      - "3000:3000"
    env_file: ./.env
    depends_on:
      - mongo_db
    restart: unless-stopped
    environment:
      - DB_HOST=mongo_db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT

volumes:
  mongo_data:
