version: '3.9'

services:
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD} 
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    # command: mongod --auth

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db
    networks:
      - backend
    restart: always

volumes:
  mongo_data:

networks:
  backend:
